### ISSUE TITLE
EDK2 Platforms - TODO List

### ISSUE THREAD

**Issue by pbatard** [pbatard/RaspberryPiPkg#2]
Keeping track here of the various items that need to be addressed for edk2-platforms integration:

- [ ] Rename `Binary` to `ATF`
- [ ] `UEFI firmware (version  built at 17:17:52 on Dec 11 2018)` in DEBUG output &rarr; Remove `version ` string in above 
- [ ] `DwUsbHostDxe` licensing issues
- [ ] Split between `Platform/RaspberryPi/Pi3` and `Silicon/Broadcom/Bcm283x`
- [ ] Add an entry to top-level `Readme.md` with a link to the rpi3 `Readme.md`
- [x] ~~Is there any chance we could rebase our DesignWare USB driver to the [latest Android OpenPlatformPkg](https://android.googlesource.com/device/linaro/bootloader/OpenPlatformPkg/+/master/Drivers/Usb/) instead of [8.0.0_r4](https://android.googlesource.com/device/linaro/bootloader/OpenPlatformPkg/+/android-8.0.0_r4/Drivers/Usb)?~~ &rarr; _Gave it a try, and I can bring and compile `DwUsbDxe` and `DwUsb3Dxe` alright but it doesn't look like these drivers alone can replace the USB Host we need. Furthermore, even after making sure I set the right base address for `DW_USB[3]_BASE` in the headers, I'm still seeing `Error: Image at 00036FAF000 start failed: Not Found` when loading the drivers_
- [ ] __ALL FILES__: Make sure we follow EDK2 coding guidelines (space before `(`, `STATIC` `<RET_TYPE>` on different lines, no inline variable init...)
- [ ] __ALL `.inf`/`.dec`/...: Make sure version is set to EDK2's most recent
- [ ] `MemoryInitPeiLib.c`: `Status = ArmConfigureMmu (MemoryTable, &TranslationTableBase, &TranslationTableSize); ` &rarr; Drop last 2 params
- [ ] `MemoryInitPeiLib.c`: Rename the `AddAnd...` to something better
- [ ] `MemoryInitPeiLib.c`: Move `ArmPlatformGetVirtualMemoryMap()` from `RaspberryPiMem.c` into this file. 
- [ ] MemoryInitPeiLib.c`: Drop `AddAndMmio(&MemoryTable[5]);`
- [ ] MemoryInitPeiLib.c`: Drop `switch (ResetType)` and use the notification functionality provided by `MdeModulePkg/Universal/ResetSystemRuntimeDxe`. Also use the generic PSCI library.
- [ ] `utils.h`: Rename the macros to something a lot more explicit. Also use `ARRAY_SIZE()` from `Base.h`
- [ ] `utils.h`: Find out if the macros are really used in more than one file and see if we can drop `utils.h` altogether
- [ ] `RpiFdtDxe/RpiFdtDxe.c`: Use `EfiBootServicesData` in `AllocatePages()`
- [ ] `RpiFirmwareDxe`: Move it forward in the series
- [ ] All: Address the "patch introduces empty line" reported by `git am`

**Comment by pbatard** [comment]
Closing this, as it is handled as tasks in GitHub projects.
